# Generated by Django 3.0 on 2020-07-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosbkk_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='assigned_user_id',
            new_name='assigned_user',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='hospitals_id',
            new_name='hospitals',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='modified_user_id',
            new_name='modified_user',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='project_subgroup_id',
            new_name='project_subgroup',
        ),
    ]
