# Generated by Django 3.0 on 2020-07-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosbkk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
    ]
