# Generated by Django 3.0 on 2020-07-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosbkk_app', '0002_auto_20200702_1537'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project_subgroup',
            managers=[
            ],
        ),
    ]
