# Generated by Django 3.0 on 2020-07-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosbkk_app', '0003_auto_20200716_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
    ]
