# Generated by Django 3.0 on 2020-07-03 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosbkk_app', '0003_auto_20200703_0836'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hospitals',
            managers=[
            ],
        ),
    ]
