# Generated by Django 3.0 on 2020-07-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosbkk_app', '0004_auto_20200703_0844'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='service',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='status',
            managers=[
            ],
        ),
    ]
